### PR TITLE
Merge pages

### PR DESCRIPTION
**Pull request by brenno263**

### CODE REVIEW

**Review by conner-c — APPROVED** [review]
Looks great! Everything looks in order and is ready to be the final essay.

**Comment by notbrayton** [comment]
Looks gucci!

**Review by SamRett — APPROVED** [review]
Do not see any changes that need to be made. I vote this is ready to send

**Comment by brenno263** [comment]
I feel good about this one. I kinda dig the more story-ish format this essay took on.

**Pull request merged**
